# Generated by Django 2.0.2 on 2018-03-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=200)),
                ('book_isbn', models.CharField(max_length=13)),
                ('book_pubtime', models.DateField()),
                ('book_borrower', models.CharField(max_length=5)),
            ],
        ),
    ]
