# Generated by Django 2.0.2 on 2018-03-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book_borrower',
            new_name='book_borrowid',
        ),
    ]
