# Generated by Django 2.0.2 on 2018-03-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180304_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_pubtime',
            field=models.CharField(max_length=20),
        ),
    ]
