# Generated by Django 2.0.3 on 2018-04-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180304_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower', models.CharField(max_length=100)),
                ('rent_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100)),
                ('return_time', models.DateTimeField()),
            ],
        ),
    ]
