# Generated by Django 2.0.3 on 2018-04-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_borrows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrows',
            name='rent_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
