# Generated by Django 2.0.3 on 2018-04-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180407_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrows',
            name='return_time',
            field=models.DateTimeField(default=None),
        ),
    ]
