# Generated by Django 2.0.3 on 2018-04-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180407_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrows',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
