# Generated by Django 2.0.2 on 2018-04-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_borrowname',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
