# Generated by Django 2.0.3 on 2018-04-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_books_book_borrowname'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_barcode',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
