# Generated by Django 2.0.3 on 2018-04-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_books_book_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_borrowid',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_isbn',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_pubtime',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
