# Generated by Django 2.0.2 on 2018-04-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180414_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_borrowid',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
