# Generated by Django 2.0.2 on 2018-04-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180423_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_barcode',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_borrowname',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
