# Generated by Django 2.0.4 on 2018-04-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180423_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(blank=True, default='', max_length=200)),
                ('book_author', models.CharField(blank=True, default='', max_length=200)),
                ('book_pubtime', models.CharField(blank=True, default='', max_length=20)),
                ('book_isbn', models.CharField(blank=True, default='', max_length=13)),
                ('book_borrowid', models.CharField(blank=True, default='', max_length=5)),
                ('book_borrowname', models.CharField(blank=True, default='', max_length=5)),
                ('book_barcode', models.CharField(blank=True, default='', max_length=5)),
            ],
        ),
    ]
