# Generated by Django 2.0.2 on 2018-04-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_newbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrows',
            name='barcode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='borrows',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='borrows',
            name='pubtime',
            field=models.CharField(default='', max_length=100),
        ),
    ]
